---
#Install packages we need before we do anything else...

- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install PolicyKit-1
  apt:
     name: policykit-1
     state: present


### CLEAN UP DEPS ###

- name: Remove unused dependencies
  apt:
    autoremove: yes
