---

 - name: Generate cluster join token
   command: kubeadm token create --print-join-command
   register: join_token

- name: Create node join command fact
  set_fact:
    join_command: "{{ join_token.stdout_lines[0] }}"